version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: samsungdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - git-actions-auto_my-network
    restart: unless-stopped

  app:
    image: ghcr.io/geonmoo2/nuxt-auto-deploy:latest  # Actions에서 빌드된 이미지를 사용
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/samsungdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - mysql
    networks:
      - git-actions-auto_my-network
    restart: unless-stopped

volumes:
  mysql-data:
    driver: local

networks:
  git-actions-auto_my-network:
    driver: bridge
