name: CI/CD Docker

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/nuxt-auto-deploy
  VERSION: ${{ github.sha }}
  NAME: go_cicd
  DOCKER_COMPOSE_FILE: /home/ec2-user/actions-runner/_work/git-actions-auto/git-actions-auto/repo/docker-compose.yml

jobs:
  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-go ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          path: repo

      - name: Print working directory
        run: pwd

      - name: List files in current directory
        run: ls -al

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Stop and remove existing containers
        run: |
          sudo docker-compose -f "./docker-compose.yml" down

      - name: Docker Compose setup
        run: |
          sudo docker-compose -f "./docker-compose.yml" pull
          sudo docker-compose -f "./docker-compose.yml" up -d --build --remove-orphans
